# https://github.com/marketplace/actions/screenshots-ci-action
name: screenshots of lunch
on:
  #schedule:
  #  # Runs "" (see https://crontab.guru)
  #  - cron: '30 4 * * 1-5'
  workflow_dispatch:
    inputs:
      url:
        description: 'The website URL (ex: https://www.google.com/)'
        required: true
        default: ''
jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    # https://playwright.dev/python/docs/ci-intro
    - name: Install pytest-playwright
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright
        python -m playwright install chrome
        python -m playwright install --with-deps
    - name: Capture screenshot
      run: |
        playwright ${{ github.event.inputs.url }} $(date +"%y-%m-%d_%H%M%S.png")