name: Package Scoop and softwares

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      team:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'team'
        # Default value if no value is explicitly provided
        default: 'Test'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-latest
    ## https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
    if:  ${{ inputs.team }}
    steps:
    - name: Execute PowerShell commands
      shell: powershell
      run: |
        ## https://github.com/ScoopInstaller/Install#for-admin
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin -ScoopDir 'D:\a\_temp\scoop'"
        scoop bucket add extras
        scoop download git 
        scoop download 7zip
        scoop download cmder
        scoop download saml2aws
        scoop download k6
        scoop download terraform
        scoop download redis
        scoop download vscode
        scoop download wget
        scoop download python
        scoop download golangci-lint

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: scoop-cache
        path: D:\a\_temp\scoop\cache