name: Package Scoop and softwares

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      team:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'team'
        # Default value if no value is explicitly provided
        default: 'Test'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-latest
    ## https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
    if:  ${{ inputs.team }}
    steps:
    - name: Execute PowerShell commands
      shell: powershell
      run: |
        ## https://github.com/ScoopInstaller/Install#for-admin
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin -ScoopDir 'D:\a\_temp\scoop'"
        scoop update
        scoop install git 7zip
        scoop list
        scoop download saml2aws
        scoop download k6
        scoop download terraform
    - name: Zip folder
      run: |
        Compress-Archive -Path D:\a\_temp\scoop -DestinationPath scoop.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: scoop
        path: scoop.zip
    
    - name: upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "scoop.zip"