name: Package Scoop and softwares required by EE IND

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      team:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'team'
        # Default value if no value is explicitly provided
        default: 'EE_IND'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    ## https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: windows-latest
    ## https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows
    if:  ${{ inputs.team }}
    steps:
    - name: Execute PowerShell commands
      shell: powershell
      run: |
        ## https://github.com/ScoopInstaller/Install#for-admin
        iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        pwd
        scoop update
        scoop download saml2aws
        scoop download k6
        scoop download terraform
        if ($env:SCOOP) {
          Write-Host "SCOOP environment variable value: $($env:SCOOP)"
        } else {
          Write-Host "SCOOP environment variable is not set."
        }